name: Continuous Integration (build, docker, deploy)

on:
    workflow_dispatch:
    push:
        branches: ["main"]

jobs:
    build:
        if: github.repository == 'crustio/ethda-scan-frontend'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v4
              with:
                  images: gavfu/scan-frontend
                  tags: |
                      type=raw,value=latest,enable=${{ github.ref_name == 'main' }}

            - name: Login to DockerHub
              if: github.event_name != 'pull_request'
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                context: .
                file: ./Dockerfile
                push: true
                cache-from: type=gha
                tags: ${{ inputs.tags || steps.meta.outputs.tags }}
                platforms: |
                  linux/amd64
                  linux/arm64/v8
                labels: ${{ steps.meta.outputs.labels }}
